apiVersion: v1
kind: Pod
metadata:
  name: nodelabelcontainer 
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo hello-manu; sleep 5; done"]
  nodeSelector:
    mynode: manukubernetes

